import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createWriteStream } from 'node:fs';
import { pipeline } from 'node:stream/promises';
import { Readable } from 'node:stream';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const version = process.env.VENIX_VERSION || JSON.parse(fs.readFileSync(path.join(root, 'package.json'))).version;
const platform = { win32: 'windows', darwin: 'darwin', linux: 'linux' }[process.platform];
const arch = { x64: 'amd64', arm64: 'arm64' }[process.arch];
if (!platform || !arch) throw new Error(`Plataforma não suportada: ${process.platform}/${process.arch}`);
const ext = platform === 'windows' ? 'zip' : 'tar.gz';
const asset = `venix_${version}_${platform}_${arch}.${ext}`;
const url = `https://github.com/LLGGJ/venix-cli/releases/download/v${version}/${asset}`;
const dir = path.join(root, '.bin');
fs.mkdirSync(dir, { recursive: true });
const archive = path.join(dir, asset);
const response = await fetch(url);
if (!response.ok) throw new Error(`Release Go não encontrada (${response.status}): ${url}`);
await pipeline(Readable.fromWeb(response.body), createWriteStream(archive));
if (platform === 'windows') execFileSync('powershell', ['-NoProfile', '-Command', `Expand-Archive -Force '${archive}' '${dir}'`]);
else execFileSync('tar', ['-xzf', archive, '-C', dir]);
const binary = path.join(dir, platform === 'windows' ? 'venix.exe' : 'venix');
if (platform !== 'windows') fs.chmodSync(binary, 0o755);
fs.writeFileSync(path.join(root, 'bin', 'venix.js'), `#!/usr/bin/env node\nimport { spawn } from 'node:child_process';\nconst p=spawn(${JSON.stringify(binary)}, process.argv.slice(2), {stdio:'inherit'}); p.on('exit', c=>process.exit(c ?? 1));\n`);
